language: minimal
before_script:
- docker build --tag narcissus .
script:
- docker run
  -e TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST
  -e TRAVIS_TEST_RESULT=$TRAVIS_TEST_RESULT
  -e TRAVIS_BRANCH=$TRAVIS_BRANCH
  -e GIT_COMMIT_SHA=$GIT_COMMIT_SHA
  -e GIT_COMMITTED_AT=$GIT_COMMITTED_AT
  -e CC_TEST_REPORTER_ID=$CC_TEST_REPORTER_ID
  narcissus npm run test:coverage
env:
  global:
    secure: P7IS6BgmPrHzprpKF5wcFKPctJoATN7LGF0WA8mcj+dpEQ9z7aGo8qcO0cuIAsB97+1AQ3WHydn9avT3pkahtKLb0UR9JhqjZT2HsfHzkur05U5F4AtHuW3C11jn7/683j3BRZqca1xIYpG72n0o9ywuYX65sUA4EcJjtd4fInYEzPSulKBROq83CvlOvH9zrimAQbUKU3wK9BDy/y7+tPMZCHkkWH5c18IO5GNd7I/J1YeqCF/6GrjNqfa2LBoO6gqvvHYyuFUTfIPmq/ln7i43U1xgLI8m5ttUzPHfPK6C3ngoEWu2Tzw6oTYkiQc2lECwvVPnYN+8e0+LxcmmzRcnXjJSI9+6NsGpK9AxhVkzz0w8T6JPgxDG/dSo4nqbZzPEIbqrzuDDMjDnI+v+wB3NtrMMVg6f8VoLiyITIJTArvYEUnFzG2pJ1/7egXOTNA9tKUEsYOFTDvDwJEkvOHVSs/qNCyLT8YjD+0nrh+gCJrxIJSRrtksqqbTzpmUpWxUPDJfPIgKHA95gXxwEbi23SgZPpunzG496A+EdFEvT+aPzMA3mjgUwmDvOxsCXNmXNc6B0Wm+juR6VeaZB2VKktS958k3m2Zbtgdk/PNrXzLFEAX6UsP2qaDgVARy+LLqXsZ+4jTsQPdVtw15940XjO2QjMEJ4X8ae5IMNcRs=
notifications:
  slack:
    secure: jmAR4q5bix9edr6CY5KubKBpayizjEs1W8PQMiylircbPj6PoAlP9vmB1d+tbtDcG1BQw5oqIS4kUhfooxqMET5M380WSklgaqWM0sy/OTFwznyARA5g2N5SBUPBTHRu7oDG2XH4O9vPCI9cTJvA5J4pKvFdgHWUsIQihHREKHIry29apq12UmIkKCPtwR4I2XpdpHmkc5RtZKb7sf48RTG2GCC4Ip0orG11g3IwVAg/CFyx/sktlLW4w7sh+FqSvkpft5YD0nj6VqVhNnBW+ppuo6ynUp8BCDs8TGBV/6GYhe/wtP4k1Fn33ZC4b4dBHEkk/XrT5f3KRQD82xjwaeCy2mhIq4tywW6OTEeZV/42oINdcoIpos8J3i/U9JY6nHy7BTeOPxhZvEmQXgFbsexSIzEiZOusXQMUZOE5/X64hdzmrTvafSsfV9NkNU/zdFWShBJK3E+8m/BCTXSLeizv7owjoN9jx4H249WWuTDrCIZN6wgB7psf0CcxlksSfSKAr83516nLiHarEUfeCd3GUMYDqKJAJxQoySBOJf5JBc1vrAmrg/oafKhn7/faVK8x3+jQ1Rrl1rL/wKw1cJA3Xiudmhq4IpKfk9ub1PhUm+t00Hr8M5SfwPAG5swyOuS2x1FptkAp88INNqEnSxKKkYPafrqGM2JOfcKQXVo=
